config/routes.rb
Rails.application.routes.draw do
  match 'product', to: 'product#multiply', via: :all

  resources :recipes
  get 'recipe/new', to: 'recipes#new', as: :alt_new_recipe
  get 'recipe/:id', to: 'recipes#show', as: :alt_recipe
  get 'recipe/:id/edit', to: 'recipes#edit', as: :alt_edit_recipe
  post 'recipe/api/new', to: 'recipes#api_create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy

  validates :name, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe

  validates :content, presence: true
end

app/models/utils/recipe_params.rb
require 'json-schema'

module Utils
  class RecipeParams
    attr_accessor :name, :photo, :ingredients, :steps

    def initialize(params)
      @name = params['name']
      @photo = params['photo']
      @ingredients = params['ingredients']
      @steps = params['steps']
    end

    def validate!
      raise StandardError unless params_present?

      validate_schema!
    end

    def to_h
      {
        'name' => @name,
        'photo' => @photo,
        'ingredients' => @ingredients,
        'steps' => @steps
      }
    end

    private

    def params_present?
      @name && @photo && @ingredients && @steps
    end

    def recipe_schema
      {
        'type' => 'object',
        'required' => %w[name photo ingredients steps],
        'properties' => {
          'name' => { 'type' => 'string' },
          'photo' => { 'type' => 'string' },
          'ingredients' => { 'type' => 'array' },
          'steps' => { 'type' => 'array' }
        }
      }
    end

    def validate_schema!
      JSON::Validator.validate!(recipe_schema, to_h)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :check_method, :check_params

  def multiply
    render json: { 'token': @hash['token'], 'product': @hash['a'] * @hash['b'] }
  end

  private

  def check_method
    render json: { 'status': 405 }, status: 405 unless request.post?
  end

  def check_params
    params.permit!
    @hash = params.require(:product).to_h
    render json: { 'status': 400 }, status: 400 if incorrect_params? || incorrect_values?
  end

  def incorrect_params?
    @hash.count != 3 || !@hash['token'].is_a?(Integer) || !@hash['a'].is_a?(Integer) || !@hash['b'].is_a?(Integer)
  end

  def incorrect_values?
    @hash['token'] <= 0 || @hash['a'] <= 0 || @hash['b'] <= 0
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token, only: :api_create

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipe/api/new
  def api_create
    recipe_params = Utils::RecipeParams.new(params)

    begin
      recipe_params.validate!
      recipe = Recipe.new(name: recipe_params.name, photo: recipe_params.photo)
      recipe.save!

      recipe_params.ingredients.each do |val|
        Ingredient.new(name: val, recipe_id: recipe.id).save!
      end

      recipe_params.steps.each do |val|
        Step.new(content: val, recipe_id: recipe.id).save!
      end

      render json: { id: recipe.id }
    rescue
      render json: { status: 422, error: 'Unprocessable Entity' }, status: 422
    end
  end

  # POST /recipes
  # POST /recipes.json
  def create
    begin
      @recipe = Recipe.new(recipe_params)
      @recipe.save!
      create_ingredients
      create_steps
      respond_to do |format|
        format.html { redirect_to alt_recipe_path(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      end
    rescue
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    begin
      update_ingredients
      update_steps
      @recipe.update!(recipe_params)
      respond_to do |format|
        format.html { redirect_to alt_recipe_path(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      end
    rescue
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def update_ingredients
    return unless params['ingredients']

    ingredients = @recipe.ingredients
    y = -1
    for y in 0..(ingredients.count - 1)
      if params['ingredients'][y].empty?
        ingredients[y].destroy
      elsif ingredients[y].name != params['ingredients'][y]
        ingredients[y].name = params['ingredients'][y]
        ingredients[y].save!
      end
    end

    for j in (y + 1)..(params['ingredients'].count - 1)
      unless params['ingredients'][j].empty?
        ingredient = Ingredient.new(name: params['ingredients'][j], recipe_id: @recipe.id)
        ingredient.save!
      end
    end
  end

  def update_steps
    return unless params['steps']

    steps = @recipe.steps
    y = -1
    for y in 0..(steps.count - 1)
      if params['steps'][y].empty?
        steps[y].destroy
      elsif steps[y].content != params['steps'][y]
        steps[y].content = params['steps'][y]
        steps[y].save!
      end
    end

    for j in (y + 1)..(params['steps'].count - 1)
      unless params['steps'][j].empty?
        step = Step.new(content: params['steps'][j], recipe_id: @recipe.id)
        step.save!
      end
    end
  end

  def create_ingredients
    return unless params['ingredients']

    for i in 0..(params['ingredients'].count - 1)
      unless params['ingredients'][i].empty?
        ingredient = Ingredient.new(name: params['ingredients'][i], recipe_id: @recipe.id)
        ingredient.save!
      end
    end
  end

  def create_steps
    return unless params['steps']

    for i in 0..(params['steps'].count - 1)
      unless params['steps'][i].empty?
        step = Step.new(content: params['steps'][i], recipe_id: @recipe.id)
        step.save!
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div data-controller="recipe">
    <div class="group">
      <label for="ingredients">Ingredients</label>
      <div id="ingredients">
        <% recipe.ingredients.each do |ingr| -%>
          <div>
            <input type="text" name="ingredients[]" value="<%= ingr.name %>">
          </div>
        <% end -%>
      </div>
      <div class="button" data-action="click->recipe#addIngredient">Add Ingredients</div>
    </div>

    <div class="group">
      <label for="steps">Steps</label>
      <div id="steps">
        <% recipe.steps.each do |step| -%>
          <div>
            <textarea name="steps[]"><%= step.content %></textarea>
          </div>
        <% end -%>
      </div>
      <div class="button" data-action="click->recipe#addStep">Add Steps</div>
    </div>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_form_new.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div data-controller="recipe">
    <div class="group">
      <label for="ingredients">Ingredients</label>
      <div id="ingredients">
        <% recipe.ingredients.each do |ingr| -%>
          <div>
            <input type="text" name="ingredients[]" value="<%= ingr.name %>">
          </div>
        <% end -%>
      </div>
      <div class="button" data-action="click->recipe#addIngredient">Add Ingredients</div>
    </div>

    <div class="group">
      <label for="steps">Steps</label>
      <div id="steps">
        <% recipe.steps.each do |step| -%>
          <div>
            <textarea name="steps[]"><%= step.content %></textarea>
          </div>
        <% end -%>
      </div>
      <div class="button" data-action="click->recipe#addStep">Add Steps</div>
    </div>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', alt_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th>Steps</th>
      <th>Ingredients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td>
          <% begin -%>
            <%= image_tag(recipe.photo, size: '25', alt: recipe.name + ' Photo') %>
          <% rescue -%>
            <%= image_tag('https://www.civhc.org/wp-content/uploads/2018/10/question-mark.png', size: '25', alt: 'Recipe Photo') %>
          <% end -%>
        </td>
        <td><%= recipe.name %></td>
        <td><%= recipe.steps.count %></td>
        <td><%= recipe.ingredients.count %></td>
        <td><%= link_to 'Show', alt_recipe_path(recipe) %></td>
        <td><%= link_to 'Edit', alt_edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', alt_new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form_new', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @recipe.name %></h1>
  <h2>Recipe</h2>
  
</p>

<div>
  <% begin -%>
    <%= image_tag(@recipe.photo, size: '128', alt: 'Recipe Photo') %>
  <% rescue -%>
    <%= image_tag('https://www.civhc.org/wp-content/uploads/2018/10/question-mark.png', size: '128', alt: 'Recipe Photo') %>
  <% end -%>
</div>

<br>

<div class="ingredients">
  <h3>Ingredients</h3>
  <ul>
    <% @recipe.ingredients.each do |ingr| -%>
      <li><%= ingr.name %></li>
    <% end -%>
  </ul>
</div>

<div class="steps">
  <h3>Steps</h3>
  <dl>
    <% i = 1 -%>
    <% @recipe.steps.each do |step| -%>
        <dt><b>Step <%= i %></b></dt>
        <dd><%= step.content %></dd>
        <% i += 1 -%>
    <% end -%>
  </dl>
</div>


<br>

<%= link_to 'Edit', alt_edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>